language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3=dev-master
    - php: 7.1
      env: TYPO3=^8.0
    - php: 7.1
      env: TYPO3=^7.6.0
    - php: 7.0
      env: TYPO3=dev-master
    - php: 7.0
      env: TYPO3=^8.0
    - php: 7.0
      env: TYPO3=^7.6.0
    - php: 5.6
      env: TYPO3=^7.6.0
    - php: 5.5
      env: TYPO3=^7.6.0
  allow_failures:
    - env: TYPO3=dev-master

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}';

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
